#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCKOcSWommZS1ZiPuznLkOGxtaXyMLUK7qfNeaVKctRCIgs8AbfLOtN3EKi/9rw3qftQlka4d6kRLj8dpnmsX0cOzDH+htzI4y7LDLfDzSxAxKBD98Y4TV5RDxIEFxyzGksVdFdTRX6C+Bxmg8bgps2ASNnvJbJ8naybMW1fAqVbGqGnhrLm9UaC19E/9KwIigiwSg33DRv+HfxIrF48wp7ldSrNnzgVLD4L9BR5T1mpLk1wsnDA+97t4nZKLBz2yFUeBfoN9YXX8f92lO6LlKiSgHl3rK5rOxN65nP70R1PuVvaq8Bm5AEUgvf6GRe+G7gx7fLsWNOLFlK7vtFiu8x aws-key #personal
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key #teacher
ssh_pwauth: true
disable_root: false
package_update: true
packages:
  - curl
  - wget
  - nginx
  - aspnetcore-runtime-6.0
write_files:
  - content: |
      [Unit]
      Description=Demo Shop
      [Service]
      WorkingDirectory=/var/www/app
      ExecStart=/usr/bin/dotnet /var/www/app/ShopDemo.dll
      Restart=always
      RestartSec=10
      KillSignal=SIGINT
      SyslogIdentifier=dotnet-example
      User=www-data
      Environment=ASPNETCORE_ENVIRONMENT=Production
      Environment=DOTNET_PRINT_TELEMETRY_MESSAGE=false
      [Install]
      WantedBy=multi-user.target
    path: /etc/systemd/system/shop-app.service
  - content: |
      server {
        listen        80;
        server_name  44.198.29.121;
        location / {
          proxy_pass         http://127.0.0.1:5000;
          proxy_http_version 1.1;
          proxy_set_header   Upgrade $http_upgrade;
          proxy_set_header   Connection keep-alive;
          proxy_set_header   Host $host;
          proxy_cache_bypass $http_upgrade;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Proto $scheme;
        }
      }
    path: /home/ubuntu/nginx
runcmd:
  - sudo mkdir /var/www
  - sudo mkdir /var/www/app
  - sudo git clone https://gitlab.com/ch-tbz-it/Stud/m346/m346scripts.git
  - sudo sed -i 's/<your-connection-string>/server=172.31.170.8;user id=admin;password=password;database=shop/g' ./m346scripts/KN05/dotnet/appsettings.json
  - sudo cp -r ./m346scripts/KN05/dotnet/* /var/www/app/
  - sudo systemctl enable shop-app.service
  - sudo systemctl start shop-app.service
  - sudo service nginx start
  - sudo cp /home/ubuntu/nginx /etc/nginx/sites-available/default
  - sudo nginx -s reload
